# Site title and subtitle. This is used in _includes/header.html
title: 'Podlove Web Player 3.0'
subtitle: 'Documentation'

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/podlove/podlove-web-player'

# Default categories (in order) to appear in the navigation
sections: [
    ['documenation', 'Documentation'],
    ['guides'      , 'Guides'],
    ['reference'   , 'Reference'],
    ['developer'   , 'Developers'],
    ['post'        , 'Posts']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: /:categories/:title

# Syntax highlighting
highlighter: pygments

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
include: ['bower_components/podlove-web-player/dist']
exclude: ['bin', 'README.md', 'bower_components/mediaelement', 'bower_components/jquery', 'node_modules']

# Use the redcarpet Markdown renderer
markdown: redcarpet
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]

gems:
  - jekyll-redirect-from

dist: '/bower_components/podlove-web-player/dist'
